version: '3.9'
services:
  php-apache:
    build: .
    volumes:
      #- ./src/:/var/www/html
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    ports:
      - 9403:80
    restart: always
    networks:
      - dev

  db:
    image: mysql
    container_name: db_test
    restart: always
    volumes:
        - db-data:/var/lib/mysql
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
        - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_test
    restart: always
    depends_on:
        - db
    ports:
        - 8080:80
    environment:
        PMA_HOST: db
    networks:
        - dev

networks:
    dev:

volumes:
    db-data:
